logging:
  config: classpath:log4j2.xml

server:
  port: 8081

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://testing_u8fn_user:5432/testing_u8fn
    username: testing_u8fn_user
    password: MDvXWfXEQf4QwewJltBy0vYGLz3YKdLO
    driverClassName: org.postgresql.Driver
  #  hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
